package DominioDoProblema;

public enum EstadoJogo {
	AGUARDANDO_USO_CARTA,
	AGUARDANDO_SELECIONAR_PECA_MOVIMENTO,
	AGUARDNADO_SELECIONAR_PECA_LOCAL,
	AGUARDANDO_SELECIONAR_PECA_ADVERSARIO,
	AGUARDANDO_SELECIONAR_DUAS_PECAS,
}
