package DominioDoProblema;

public enum EstadoJogo {
	AGUARDANDO_USO_CARTA,
	AGUARDANDO_SELECIONAR_PECA_MOVIMENTO,
	AGUARDANDO_SELECIONAR_POSICAO_MOVIMENTO,
	AGUARDANDO_SELECIONAR_POSICAO,
	AGUARDNADO_SELECIONAR_PECA_LOCAL,
	AGUARDANDO_SELECIONAR_PECA_ADVERSARIA,
	AGUARDANDO_SELECIONAR_PECA_ADVERSARIA_NAO_REI,
	AGUARDANDO_SELECIONAR_PECA_LOCAL_NAO_REI, 
	AGUARDANDO_ADVERSARIO,
	ENVIANDO_JOGADA,
}
