package DominioDoProblema;

public enum Respostas {
	NADA,
	NAO_EH_O_MOMENTO,
	SELECIONAR_UMA_PECA_LOCAL,
	SELECIONAR_UMA_PECA_LOCAL_NAO_REI,
	SELECIONAR_UMA_PECA_ADVERSARIA,
	SELECIONAR_LOCAL_E_ADVERSARIA_NAO_REI,
	SELECIONAR_TORRE,
}
