package DominioDoProblema;

public enum Respostas {
	ENVIAR_JOGADA,
	NAO_EH_O_MOMENTO,
	SELECIONAR_UMA_PECA_LOCAL,
	SELECIONAR_UMA_PECA_LOCAL_NAO_REI,
	SELECIONAR_UMA_PECA_ADVERSARIA,
	SELECIONAR_UMA_PECA_ADVERSARIA_NAO_REI,
	SELECIONAR_POSICAO,
	VITORIA_DO_OPONENTE, 
	OK, 
	USAR_CARTA,
	AGUARDAR_ADVERSARIO, 
	SEM_CARTA_USADA
}
