package DominioDoProblema.Cartas;

public enum CartaIdentificacao {
	CORREDORES_EXPERIENTES,
	ESCUDOS,
	ESPIAR,
	MAOS_AO_ALTO,
	MOVIMENTO_BRUSCO,
	RECICLAGEM,
	SACRIFICIO,
	SAIR_PELA_TANGENTE,
	SAVE_THE_KING,
	SILENCIO_POR_FAVOR,
}

