package InterfaceGrafica;

public enum TiposCartas {
	SAIR_PELA_TANGENTE, 
	MOVIMENTO_BRUSCO, 
	SAVE_THE_KING, 
	SILENCIO_POR_FAVOR, 
	MAOS_AO_ALTO, 
	CORREDORES_EXPERIENTES, 
	ESCUDOS, 
	RECICLAGEM, 
	SACRIFICIO_NECESSARIO, 
	ESPIAR,
	DEFAULT
}
